// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dotnetExamTrainer.Models;

namespace dotnetExamTrainer.Migrations
{
    [DbContext(typeof(ExamTrainerContext))]
    partial class ExamTrainerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("dotnetExamTrainer.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string[]>("AnswerText")
                        .HasColumnType("text[]");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<int>("RightAnswer")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("dotnetExamTrainer.Models.TakenExam", b =>
                {
                    b.Property<int>("AmountAnsweredRight")
                        .HasColumnType("integer");

                    b.Property<int>("AmountAnsweredWrong")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int[]>("QuestionsAnsweredRight")
                        .HasColumnType("integer[]");

                    b.Property<int[]>("QuestionsAnsweredWrong")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("Taken")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone");

                    b.ToTable("TakenExams");
                });
#pragma warning restore 612, 618
        }
    }
}
